### Add an Investment (User ID in URL)
POST http://localhost:8080/investments/1
Content-Type: application/json

{
  "name": "Bitcoin",
  "balance": 5000.00,
  "category": "CRYPTO",
  "units": 0.1,
  "pricePerUnit": 50000.00
}

### Get All Investments for a User
GET http://localhost:8080/investments/1

### Update an Investment
PUT http://localhost:8080/investments/1/2
Content-Type: application/json

{
  "name": "Ethereum",
  "balance": 3000.00,
  "category": "CRYPTO",
  "units": 2,
  "pricePerUnit": 1500.00
}


### Delete an Investment
DELETE http://localhost:8080/investments/1


### Create a new transaction (Stock Buy)
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "type": "STOCK_BUY",
  "amount": 500.00,
  "description": "Buying Apple stocks",
  "financialOptionId": 2,
  "recipientOrStockSymbol": "AAPL",
  "quantity": 5
}

### Get all transactions
GET http://localhost:8080/transactions
