version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: finance-db
    restart: always
    environment:
      POSTGRES_USER: gvendra
      POSTGRES_PASSWORD: 56689272
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
