spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: gvendra
    password: 56689272
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
